name: Pull Request Locally Test Merge Into Master

on:
  pull_request:
    branches:
      - master

jobs:
  buildTestlocallyMergeMasterIntoBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print Environment Variables
        run: printenv
      - name: Build Docker Image
        id: build_docker_image
        run: |
          docker build --tag git-issue-creation:${GITHUB_HEAD_REF:-${GITHUB_REF##*/}} \
            --build-arg "GITHUB_HEAD_REF=${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}" \
            --build-arg "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}" \
            build/docker
      - name: Slack Notification
        id: slack_notification
        uses: bryan-nice/slack-notification@1.0.2
        if: failure()
        env:
          SLACK_CHANNEL: git-issue-creation
          SLACK_COLOR: '#3278BD'
          SLACK_TITLE: 'Failed to build on GitHub Commit SHA ${{ github.sha }}'
          SLACK_MESSAGE: |
            Please review git actions log and trouble shoot the build failure.
            The commit SHA is: _${{ github.sha }}_.
          SLACK_USERNAME: git-issue-creation
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTION: ${{ github.action }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_WORKFLOW: ${{ github.workflow }}

